const pages = [
  {
    "name": "KycEngine",
    "content": "import Navbar from '@/components/Navbar';\nimport Footer from '@/components/Footer';\nimport CTASection from '@/components/CTASection';\nimport { CheckCircle2, ArrowRight } from 'lucide-react';\n\nconst KycEngine = () => (\n  <div className='min-h-screen bg-background flex flex-col'>\n    <Navbar />\n    <main className='flex-1 pt-32 pb-10'>\n      <section className='container mx-auto px-6 mb-24 max-w-4xl text-center'>\n        <h1 className='text-4xl md:text-5xl font-display font-bold text-foreground mb-6'>KYC Engine</h1>\n        <p className='text-xl text-muted-foreground mb-10'>Verify identities instantly with bank-grade security. Our KYC Engine aggregates data from over 40+ official registries across India.</p>\n      </section>\n      <section className='container mx-auto px-6 mb-24 grid md:grid-cols-3 gap-8'>\n        {[ {t: 'Instant Verification', d:'Pre-integrated APIs.'}, {t: 'Video KYC', d:'Secure, real-time video streaming.'}, {t: 'Fraud Detection', d:'Advanced liveness checks.'} ].map((f, i) => (\n          <div key={i} className='p-8 border border-border/60 rounded-2xl bg-card'><div className='w-12 h-12 bg-primary/10 rounded-xl mb-4 flex items-center justify-center'><CheckCircle2 className='text-primary'/></div><h3 className='text-xl font-bold mb-2'>{f.t}</h3><p className='text-muted-foreground'>{f.d}</p></div>\n        ))}\n      </section>\n    </main>\n    <CTASection />\n    <Footer />\n  </div>\n);\nexport default KycEngine;"
  },
  {
    "name": "CreditScoring",
    "content": "import Navbar from '@/components/Navbar';\nimport Footer from '@/components/Footer';\nimport CTASection from '@/components/CTASection';\nimport { CheckCircle2, ArrowRight } from 'lucide-react';\n\nconst CreditScoring = () => (\n  <div className='min-h-screen bg-background flex flex-col'>\n    <Navbar />\n    <main className='flex-1 pt-32 pb-10'>\n      <section className='container mx-auto px-6 mb-24 max-w-4xl text-center'>\n        <h1 className='text-4xl md:text-5xl font-display font-bold text-foreground mb-6'>Credit Scoring</h1>\n        <p className='text-xl text-muted-foreground mb-10'>Deploy sophisticated ML models directly into your lending pipeline.</p>\n      </section>\n      <section className='container mx-auto px-6 mb-24 grid md:grid-cols-3 gap-8'>\n        {[ {t: 'Alternative Data', d:'Incorporate telecom and device data.'}, {t: 'Explainable AI', d:'Detailed reason codes.'}, {t: 'Custom Scorecards', d:'Bring your own logic instantly.'} ].map((f, i) => (\n          <div key={i} className='p-8 border border-border/60 rounded-2xl bg-card'><div className='w-12 h-12 bg-primary/10 rounded-xl mb-4 flex items-center justify-center'><CheckCircle2 className='text-primary'/></div><h3 className='text-xl font-bold mb-2'>{f.t}</h3><p className='text-muted-foreground'>{f.d}</p></div>\n        ))}\n      </section>\n    </main>\n    <CTASection />\n    <Footer />\n  </div>\n);\nexport default CreditScoring;"
  },
  {
    "name": "RulesEngine",
    "content": "import Navbar from '@/components/Navbar';\nimport Footer from '@/components/Footer';\nimport CTASection from '@/components/CTASection';\nimport { CheckCircle2, ArrowRight } from 'lucide-react';\n\nconst RulesEngine = () => (\n  <div className='min-h-screen bg-background flex flex-col'>\n    <Navbar />\n    <main className='flex-1 pt-32 pb-10'>\n      <section className='container mx-auto px-6 mb-24 max-w-4xl text-center'>\n        <h1 className='text-4xl md:text-5xl font-display font-bold text-foreground mb-6'>Rules Engine</h1>\n        <p className='text-xl text-muted-foreground mb-10'>Build and deploy underwriting workflows without writing code.</p>\n      </section>\n      <section className='container mx-auto px-6 mb-24 grid md:grid-cols-3 gap-8'>\n        {[ {t: 'Visual Builder', d:'Drag-and-drop conditions.'}, {t: 'A/B Testing', d:'Run challenger policies in shadow mode.'}, {t: 'Real-time Deployment', d:'Apply policy updates instantly.'} ].map((f, i) => (\n          <div key={i} className='p-8 border border-border/60 rounded-2xl bg-card'><div className='w-12 h-12 bg-primary/10 rounded-xl mb-4 flex items-center justify-center'><CheckCircle2 className='text-primary'/></div><h3 className='text-xl font-bold mb-2'>{f.t}</h3><p className='text-muted-foreground'>{f.d}</p></div>\n        ))}\n      </section>\n    </main>\n    <CTASection />\n    <Footer />\n  </div>\n);\nexport default RulesEngine;"
  },
  {
    "name": "ApiDocs",
    "content": "import Navbar from '@/components/Navbar';\nimport Footer from '@/components/Footer';\n\nconst ApiDocs = () => (\n  <div className='min-h-screen bg-background flex flex-col'>\n    <Navbar />\n    <main className='flex-1 pt-32 pb-20'>\n      <section className='container mx-auto px-6 max-w-4xl'>\n        <h1 className='text-4xl md:text-5xl font-display font-bold text-foreground mb-12'>API Documentation</h1>\n        <div className='space-y-12'><p className='text-xl text-muted-foreground'>Arera provides a RESTful API designed to be integrated in minutes.</p>\n        <div className='p-6 bg-secondary/30 rounded-xl border border-border/50'><h3 className='text-xl font-bold mb-4 font-mono'>POST /v1/applications</h3><p className='mb-4 text-muted-foreground'>Creates a new loan application and triggers asynchronous underwriting.</p></div>\n        <div className='p-8 border border-primary/20 bg-primary/5 rounded-2xl flex justify-between items-center outline-none'><div><h4 className='font-bold text-lg mb-1'>Looking for a full reference?</h4><p className='text-muted-foreground'>Log in to your developer dashboard.</p></div><button className='px-6 py-3 bg-primary text-primary-foreground rounded-lg font-bold'>Go to Dashboard</button></div>\n        </div>\n      </section>\n    </main>\n    <Footer />\n  </div>\n);\nexport default ApiDocs;"
  },
  {
    "name": "About",
    "content": "import Navbar from '@/components/Navbar';\nimport Footer from '@/components/Footer';\n\nconst About = () => (\n  <div className='min-h-screen bg-background flex flex-col'>\n    <Navbar />\n    <main className='flex-1 pt-32 pb-20'>\n      <section className='container mx-auto px-6 max-w-4xl'>\n        <h1 className='text-4xl md:text-5xl font-display font-bold text-foreground mb-12'>About Arera</h1>\n        <p className='text-2xl font-light leading-relaxed mb-10 text-muted-foreground'>We are rebuilding the infrastructure that powers India\\'s lending ecosystem.</p>\n        <div className='grid md:grid-cols-2 gap-12 mt-12'>\n          <div><h3 className='text-2xl font-bold mb-4'>Our Mission</h3><p className='mb-6 leading-relaxed text-muted-foreground'>Credit is the engine of economic growth. Yet, for millions of Indians and thousands of small businesses, accessing fair credit is still hindered by outdated infrastructure, manual processes, and fragmented data.</p><p className='leading-relaxed text-muted-foreground'>Arera AI was founded with a singular focus: to equip every NBFC, bank, and fintech with world-class underwriting technology, enabling them to disburse instantly, securely, and at scale.</p></div>\n          <div className='relative rounded-2xl overflow-hidden min-h-[300px] bg-secondary/50 flex items-center justify-center border border-border/50'><div className='text-center'><div className='text-5xl font-display font-bold text-primary mb-2'>5BN+</div><div className='text-sm uppercase tracking-widest text-muted-foreground font-semibold'>Data points processed</div></div></div>\n        </div>\n      </section>\n    </main>\n    <Footer />\n  </div>\n);\nexport default About;"
  },
  {
    "name": "Careers",
    "content": "import Navbar from '@/components/Navbar';\nimport Footer from '@/components/Footer';\n\nconst Careers = () => (\n  <div className='min-h-screen bg-background flex flex-col'>\n    <Navbar />\n    <main className='flex-1 pt-32 pb-20'>\n      <section className='container mx-auto px-6 max-w-4xl'>\n        <h1 className='text-4xl md:text-5xl font-display font-bold text-foreground mb-12'>Careers at Arera</h1>\n        <p className='text-xl text-muted-foreground mb-12'>Join a team of engineers, data scientists, and risk experts building the future of financial infrastructure.</p>\n        <h3 className='text-2xl font-bold mb-6 pt-8 border-t border-border/50'>Open Positions</h3>\n        <div className='space-y-4'>\n          {[ { role: 'Senior Backend Engineer (Go)', loc: 'Bengaluru / Remote' }, { role: 'Machine Learning Engineer', loc: 'Bengaluru' }, { role: 'Product Manager', loc: 'Mumbai / Remote' } ].map((j, i) => (\n            <div key={i} className='flex justify-between items-center p-6 border border-border/60 rounded-xl hover:border-primary/50 hover:bg-primary/5 transition cursor-pointer'><div><h4 className='font-bold text-lg text-foreground'>{j.role}</h4><div className='text-sm text-muted-foreground mt-1'>{j.loc}</div></div><div className='px-4 py-2 bg-secondary rounded-lg text-sm font-medium'>Apply &rarr;</div></div>\n          ))}\n        </div>\n      </section>\n    </main>\n    <Footer />\n  </div>\n);\nexport default Careers;"
  },
  {
    "name": "Blog",
    "content": "import Navbar from '@/components/Navbar';\nimport Footer from '@/components/Footer';\n\nconst Blog = () => (\n  <div className='min-h-screen bg-background flex flex-col'>\n    <Navbar />\n    <main className='flex-1 pt-32 pb-20'>\n      <section className='container mx-auto px-6 max-w-4xl'>\n        <h1 className='text-4xl md:text-5xl font-display font-bold text-foreground mb-12'>Blog & Insights</h1>\n        <p className='text-xl text-muted-foreground mb-12'>Thoughts on lending technology, product updates, and engineering deep dives.</p>\n        <div className='grid md:grid-cols-2 gap-8'>\n          {[ { d: 'Oct 12, 2026', t: 'Scaling our ML feature pipeline', c: 'Engineering' }, { d: 'Sep 28, 2026', t: 'Why NBFCs move away from legacy LOS', c: 'Industry' }, { d: 'Sep 15, 2026', t: 'Real-time CERSAI integration', c: 'Product' } ].map((p, i) => (\n            <div key={i} className='p-8 border border-border/50 rounded-2xl hover:bg-secondary/20 transition cursor-pointer flex flex-col justify-between min-h-[220px]'><div><span className='text-xs font-bold text-primary tracking-widest uppercase mb-4 block'>{p.c}</span><h3 className='text-xl font-bold text-foreground leading-tight mb-4'>{p.t}</h3></div><div className='text-sm text-muted-foreground font-medium'>{p.d}</div></div>\n          ))}\n        </div>\n      </section>\n    </main>\n    <Footer />\n  </div>\n);\nexport default Blog;"
  },
  {
    "name": "Contact",
    "content": "import Navbar from '@/components/Navbar';\nimport Footer from '@/components/Footer';\n\nconst Contact = () => (\n  <div className='min-h-screen bg-background flex flex-col'>\n    <Navbar />\n    <main className='flex-1 pt-32 pb-20'>\n      <section className='container mx-auto px-6 max-w-4xl'>\n        <h1 className='text-4xl md:text-5xl font-display font-bold text-foreground mb-12'>Contact Us</h1>\n        <div className='grid md:grid-cols-2 gap-16'>\n          <form className='space-y-6'><div className='space-y-2'><label className='text-sm font-semibold'>Work Email</label><input className='w-full bg-secondary/30 border border-border/60 rounded-lg px-4 py-3 text-foreground' placeholder='name@company.com' /></div><div className='space-y-2'><label className='text-sm font-semibold'>Company Name</label><input className='w-full bg-secondary/30 border border-border/60 rounded-lg px-4 py-3 text-foreground' placeholder='Acme Finance' /></div><button type='button' className='w-full bg-primary text-primary-foreground font-bold py-3 rounded-lg'>Send Message</button></form>\n          <div><h3 className='text-xl font-bold mb-4'>Offices</h3><div className='p-6 border border-border/50 rounded-xl mb-6'><h4 className='font-bold text-foreground mb-2'>Bengaluru (HQ)</h4><p className='text-muted-foreground text-sm'>Arera Heights, Koramangala<br/>Karnataka, India</p></div></div>\n        </div>\n      </section>\n    </main>\n    <Footer />\n  </div>\n);\nexport default Contact;"
  },
  {
    "name": "PrivacyPolicy",
    "content": "import Navbar from '@/components/Navbar';\nimport Footer from '@/components/Footer';\n\nconst PrivacyPolicy = () => (\n  <div className='min-h-screen bg-background flex flex-col'>\n    <Navbar />\n    <main className='flex-1 pt-32 pb-20'>\n      <section className='container mx-auto px-6 max-w-4xl'>\n        <h1 className='text-4xl md:text-5xl font-display font-bold text-foreground mb-12'>Privacy Policy</h1>\n        <div className='space-y-6 text-muted-foreground leading-relaxed'><p>Last updated: April 14, 2026</p><h3 className='text-xl font-bold text-foreground mt-8 mb-4'>1. Information We Collect</h3><p>Arera AI acts primarily as a data processor for our NBFC and financial institution clients.</p><h3 className='text-xl font-bold text-foreground mt-8 mb-4'>2. How We Use Data</h3><p>Data is strictly used to perform underwriting and KYC verification under enterprise agreements.</p></div>\n      </section>\n    </main>\n    <Footer />\n  </div>\n);\nexport default PrivacyPolicy;"
  },
  {
    "name": "TermsOfService",
    "content": "import Navbar from '@/components/Navbar';\nimport Footer from '@/components/Footer';\n\nconst TermsOfService = () => (\n  <div className='min-h-screen bg-background flex flex-col'>\n    <Navbar />\n    <main className='flex-1 pt-32 pb-20'>\n      <section className='container mx-auto px-6 max-w-4xl'>\n        <h1 className='text-4xl md:text-5xl font-display font-bold text-foreground mb-12'>Terms of Service</h1>\n        <div className='space-y-6 text-muted-foreground leading-relaxed'><p>By accessing or using Arera\\'s API, you agree to be bound by these Terms.</p><h3 className='text-xl font-bold text-foreground mt-8 mb-4'>Service Level Agreement (SLA)</h3><p>Arera guarantees a 99.9% uptime for core API services.</p><h3 className='text-xl font-bold text-foreground mt-8 mb-4'>Compliance</h3><p>Clients must ensure they possess the necessary user consent as per DPDP Act and RBI master directions.</p></div>\n      </section>\n    </main>\n    <Footer />\n  </div>\n);\nexport default TermsOfService;"
  },
  {
    "name": "Security",
    "content": "import Navbar from '@/components/Navbar';\nimport Footer from '@/components/Footer';\n\nconst Security = () => (\n  <div className='min-h-screen bg-background flex flex-col'>\n    <Navbar />\n    <main className='flex-1 pt-32 pb-20'>\n      <section className='container mx-auto px-6 max-w-4xl'>\n        <h1 className='text-4xl md:text-5xl font-display font-bold text-foreground mb-12'>Security at Arera</h1>\n        <p className='text-xl text-muted-foreground mb-12'>Security is foundational. We process sensitive PII and we treat our infrastructure appropriately.</p>\n        <div className='grid md:grid-cols-3 gap-6 mb-16'><div className='p-8 border border-border/50 rounded-xl bg-secondary/20 items-center text-center'><div className='text-4xl mb-4'>🛡️</div><h4 className='font-bold text-lg mb-2'>SOC 2 Type II</h4><p className='text-sm text-muted-foreground'>Certified Security.</p></div><div className='p-8 border border-border/50 rounded-xl bg-secondary/20 items-center text-center'><div className='text-4xl mb-4'>🔒</div><h4 className='font-bold text-lg mb-2'>ISO 27001</h4><p className='text-sm text-muted-foreground'>InfoSec System.</p></div><div className='p-8 border border-border/50 rounded-xl bg-secondary/20 items-center text-center'><div className='text-4xl mb-4'>🇮🇳</div><h4 className='font-bold text-lg mb-2'>Local Data</h4><p className='text-sm text-muted-foreground'>Stored in India.</p></div></div>\n        <div className='p-8 border border-border/60 rounded-2xl bg-card'><h3 className='text-2xl font-bold mb-6'>Penetration Testing</h3><p className='text-muted-foreground mb-4'>We engage third-party security firms to perform comprehensive tests on our platform annually.</p><a href='#' className='font-semibold text-primary'>Request our latest pentest report &rarr;</a></div>\n      </section>\n    </main>\n    <Footer />\n  </div>\n);\nexport default Security;"
  }
];

const fs = require('fs');
const path = require('path');
const pagesDir = path.join(__dirname, 'src', 'pages');

pages.forEach(p => {
  fs.writeFileSync(path.join(pagesDir, p.name + '.tsx'), p.content);
});

console.log('Fleshed out pages created successfully.');
